@url = http://localhost:5000


###
GET {{url}}/reservations


###
GET {{url}}/reservations/1


###
POST {{url}}/reservations
Content-Type: application/json

{
  "parkingSpotName": "P1",
  "employeeName": "Joe Doe",
  "licencePlate": "XYZ"
}



###
PUT {{url}}/reservations/1
Content-Type: application/json

{
  "licencePlate": "XYZZ"
}



###
DELETE {{url}}/reservations/1