@url = http://localhost:5000
@reservationId = 1
       
###
GET {{url}}/reservations


###
GET {{url}}/reservations/{{reservationId}}


###
POST {{url}}/reservations
Content-Type: application/json

{
  "employeeName": "Joe Doe",
  "parkingSpotName": "P1",
  "licencePlate": "XYZ",
  "date": "2022-08-27",
}



###
PUT {{url}}/reservations/1
Content-Type: application/json

{
  "licencePlate": "XYZZ"
}



###
DELETE {{url}}/reservations/1