@url = http://localhost:5000
@reservationId = 00000000-0000-0000-0000-000000000001
@parkingSpotId = 00000000-0000-0000-0000-000000000001
@userId = 00000000-0000-0000-0000-000000000001


###
POST {{url}}/users
Content-Type: application/json

{
  "email": "mail1@mail.com",
  "username": "user1",
  "password": "Password1",
  "fullName": "John Doe",
  "role": "user"
}

###
GET {{url}}/users

###
GET {{url}}/users/{{userId}}


###
GET {{url}}


###
GET {{url}}/parking-spots


###
GET {{url}}/parking-spots/{{reservationId}}


###
POST {{url}}/parking-spots/{{parkingSpotId}}/reservations/vehicle
Content-Type: application/json

{
  "capacity": 1,
  "employeeName": "Joe Doe",
  "licensePlate": "XYZ123",
  "date": "2022-10-18"
}

###
POST {{url}}/parking-spots/reservations/cleaning
Content-Type: application/json

{
  "date": "2022-10-18"
}


###
PUT {{url}}/parking-spots/reservations/{{reservationId}}
Content-Type: application/json

{
  "licencePlate": "XYZ321"
}



###
DELETE {{url}}/parking-spots/reservations/{{reservationId}}